package view;

import controller.Ban_NhanSuController;
import controller.Luong_NhanSuController;
import controller.NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.BanModel;
import model.Ban_NhanSuModel;
import model.Luong_NhanSuModel;
import model.NhanSuModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author .K
 */
public class ChiTietNhanSu extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietNhanSu
     */
    ArrayList<NhanSuModel> danhsach = new ArrayList<>();
    ArrayList<Luong_NhanSuModel> dsLNS = new ArrayList<>();
    ArrayList<Ban_NhanSuModel> dsBNS = new ArrayList<>();
    String id;
    String MaTV;
    /**
     * Creates new form ChiTietNhanSu
     */
    public ChiTietNhanSu(String id, String MaNS,String MaTV) throws IOException {
        this.id = id;
        this.MaTV = MaTV;
        initComponents();
        danhsach = NhanSuController.ReadToFile();
        dsLNS = Luong_NhanSuController.ReadToFile();
        dsBNS = Ban_NhanSuController.ReadToFile();
        showresult(MaNS);
    }

    public void showresult(String maNS) {
        NhanSuModel s = new NhanSuModel(maNS);
        if (danhsach.contains(s)) {
            NhanSuModel ns = danhsach.get(danhsach.indexOf(s));
            txt_mNS.setText(ns.getMaNS());
            txt_hoTen.setText(ns.getHoTen());
            txt_ngaySinh.setText(ns.getNgaySinh());
            if (ns.isGioiTinh()) {
                txt_gioiTinh.setText("Nam");
            } else {
                txt_gioiTinh.setText("Nữ");
            }
            txt_queQuan.setText(ns.getQueQuan());
            txt_cCCD.setText(ns.getCCCD());
            txt_soDT.setText(ns.getSoDT());
            txt_danToc.setText(ns.getDanToc());
            ArrayList<Ban_NhanSuModel> dsBanCuaNs = Ban_NhanSuController.TimBanTheoNhanSu(dsBNS, ns);
            if (dsBanCuaNs.size() <= 0) {
                txt_phongBan.setText("Chưa có");
            } else {
                txt_phongBan.setText(dsBanCuaNs.get(0).getBan().getMaBan());
            }
            txt_chucVu.setText(ns.getChucVu());
            txt_trinhDo.setText(ns.getTrinhDo());
            txt_chuyenNganh.setText(ns.getChuyenNganh());
            if (ns.isLoaiNS()) {
                txt_loaiNS.setText("Hợp đồng");
            } else {
                txt_loaiNS.setText("Không hợp đồng");
            }
            txt_ngayTG.setText(ns.getNgayTG());
            txt_hanHD.setText(ns.getHanHD());
            ArrayList<Luong_NhanSuModel> dsLuongCuaNs = new ArrayList<>();
            dsLuongCuaNs.addAll(Luong_NhanSuController.TimLuongTheoNhanSu(dsLNS, ns));
            if (dsLuongCuaNs.size() <= 0) {
                txt_luong.setText("Chưa có");
            } else {
                txt_luong.setText(dsLuongCuaNs.get(0).getLuong().getLoaiNS());

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_mNS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cCCD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_queQuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_gioiTinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_danToc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_phongBan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_chucVu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_trinhDo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_ngayTG = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_chuyenNganh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_hanHD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_soDT = new javax.swing.JTextField();
        txt_loaiNS = new javax.swing.JTextField();
        btn_thoat = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txt_luong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã Nhân Sự");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 97, -1));

        txt_mNS.setBackground(new java.awt.Color(250, 250, 250));
        txt_mNS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_mNS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_mNS.setEnabled(false);
        txt_mNS.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_mNS.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_mNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 99, -1));

        jLabel3.setText("Họ Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 97, -1));

        txt_hoTen.setBackground(new java.awt.Color(250, 250, 250));
        txt_hoTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_hoTen.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_hoTen.setEnabled(false);
        txt_hoTen.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_hoTen.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_hoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 99, -1));

        jLabel4.setText("Số CCCD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 97, -1));

        txt_cCCD.setBackground(new java.awt.Color(250, 250, 250));
        txt_cCCD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cCCD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_cCCD.setEnabled(false);
        txt_cCCD.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_cCCD.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_cCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 99, -1));

        jLabel5.setText("Ngày Sinh");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 97, -1));

        txt_ngaySinh.setBackground(new java.awt.Color(250, 250, 250));
        txt_ngaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ngaySinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_ngaySinh.setEnabled(false);
        txt_ngaySinh.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_ngaySinh.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 99, -1));

        jLabel6.setText("Quê Quán");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 97, -1));

        txt_queQuan.setBackground(new java.awt.Color(250, 250, 250));
        txt_queQuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_queQuan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_queQuan.setEnabled(false);
        txt_queQuan.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_queQuan.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_queQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 99, -1));

        jLabel7.setText("Giới Tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 97, -1));

        txt_gioiTinh.setBackground(new java.awt.Color(250, 250, 250));
        txt_gioiTinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_gioiTinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_gioiTinh.setEnabled(false);
        txt_gioiTinh.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_gioiTinh.setPreferredSize(new java.awt.Dimension(64, 22));
        txt_gioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gioiTinhActionPerformed(evt);
            }
        });
        getContentPane().add(txt_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 99, -1));

        jLabel8.setText("Dân Tộc");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 97, -1));

        txt_danToc.setBackground(new java.awt.Color(250, 250, 250));
        txt_danToc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_danToc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_danToc.setEnabled(false);
        txt_danToc.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_danToc.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_danToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 99, -1));

        jLabel9.setText("Phòng Ban");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 97, -1));

        txt_phongBan.setBackground(new java.awt.Color(250, 250, 250));
        txt_phongBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_phongBan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_phongBan.setEnabled(false);
        txt_phongBan.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_phongBan.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_phongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 99, -1));

        jLabel10.setText("Chức Vụ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 97, -1));

        txt_chucVu.setBackground(new java.awt.Color(250, 250, 250));
        txt_chucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_chucVu.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_chucVu.setEnabled(false);
        txt_chucVu.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_chucVu.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_chucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 99, -1));

        jLabel11.setText("Trình Độ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 97, -1));

        txt_trinhDo.setBackground(new java.awt.Color(250, 250, 250));
        txt_trinhDo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_trinhDo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_trinhDo.setEnabled(false);
        txt_trinhDo.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_trinhDo.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_trinhDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 99, -1));

        jLabel12.setText("Ngày Tham Gia");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 97, -1));

        txt_ngayTG.setBackground(new java.awt.Color(250, 250, 250));
        txt_ngayTG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ngayTG.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_ngayTG.setEnabled(false);
        txt_ngayTG.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_ngayTG.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_ngayTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 99, -1));

        jLabel13.setText("Loại Nhân Sự");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 97, -1));

        jLabel14.setText("Chuyên Ngành");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 97, -1));

        txt_chuyenNganh.setBackground(new java.awt.Color(250, 250, 250));
        txt_chuyenNganh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_chuyenNganh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_chuyenNganh.setEnabled(false);
        txt_chuyenNganh.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_chuyenNganh.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_chuyenNganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 99, -1));

        jLabel15.setText("Hạn Hợp Đồng");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 97, -1));

        txt_hanHD.setBackground(new java.awt.Color(250, 250, 250));
        txt_hanHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_hanHD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_hanHD.setEnabled(false);
        txt_hanHD.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_hanHD.setPreferredSize(new java.awt.Dimension(64, 22));
        txt_hanHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hanHDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hanHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 99, -1));

        jLabel16.setText("Số Điện Thoại");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 97, -1));

        txt_soDT.setBackground(new java.awt.Color(250, 250, 250));
        txt_soDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_soDT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_soDT.setEnabled(false);
        txt_soDT.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_soDT.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_soDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 99, -1));

        txt_loaiNS.setBackground(new java.awt.Color(250, 250, 250));
        txt_loaiNS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_loaiNS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_loaiNS.setEnabled(false);
        txt_loaiNS.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_loaiNS.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_loaiNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 99, -1));

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel29.setText("Lương");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        txt_luong.setBackground(new java.awt.Color(250, 250, 250));
        txt_luong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_luong.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_luong.setEnabled(false);
        txt_luong.setMinimumSize(new java.awt.Dimension(64, 22));
        txt_luong.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(txt_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 99, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        switch (MaTV) {
            case "QLL" ->  {
                QuanLyLuong f;
                try {
                    f = new QuanLyLuong(id);
                    f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    f.setLocationRelativeTo(null);
                    f.setResizable(false);
                    f.setVisible(true);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ChiTietNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "XNSTB" -> {
                XemNhanSuTrongBan f;
                try {
                    f = new XemNhanSuTrongBan(id,new BanModel("","",null),null);
                    f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    f.setLocationRelativeTo(null);
                    f.setResizable(false);
                    f.setVisible(true);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ChiTietNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "QLTTNS" -> {
                QuanLyThongTinNhanSu f;
                try {
                    f = new QuanLyThongTinNhanSu(id);
                    f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    f.setLocationRelativeTo(null);
                    f.setResizable(false);
                    f.setVisible(true);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ChiTietNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            default -> {
                Main f;
                try {
                    f = new Main(id);
                    f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    f.setLocationRelativeTo(null);
                    f.setResizable(false);
                    f.setVisible(true);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ChiTietNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void txt_gioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gioiTinhActionPerformed

    private void txt_hanHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hanHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hanHDActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_cCCD;
    private javax.swing.JTextField txt_chucVu;
    private javax.swing.JTextField txt_chuyenNganh;
    private javax.swing.JTextField txt_danToc;
    private javax.swing.JTextField txt_gioiTinh;
    private javax.swing.JTextField txt_hanHD;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_loaiNS;
    private javax.swing.JTextField txt_luong;
    private javax.swing.JTextField txt_mNS;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_ngayTG;
    private javax.swing.JTextField txt_phongBan;
    private javax.swing.JTextField txt_queQuan;
    private javax.swing.JTextField txt_soDT;
    private javax.swing.JTextField txt_trinhDo;
    // End of variables declaration//GEN-END:variables
}
