/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TaiKhoanController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.AccountModel;

/**
 *
 * @author .K
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_taiKhoan = new javax.swing.JTextField();
        txt_matKhau = new javax.swing.JPasswordField();
        btn_dangNhap = new javax.swing.JButton();
        lb_thongbao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setLabelFor(txt_taiKhoan);
        jLabel2.setText("Tài Khoản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 355, 67, 28));

        jLabel3.setText("Mật Khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 395, 67, 25));
        getContentPane().add(txt_taiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 163, -1));

        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 163, -1));

        btn_dangNhap.setText("Đăng Nhập");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));
        getContentPane().add(lb_thongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 160, 22));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        ArrayList<AccountModel> danhsach = new ArrayList<>();
        String tk = txt_taiKhoan.getText();
        String mk = txt_matKhau.getText();
        try {
            danhsach = TaiKhoanController.danh_sach_TK();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (txt_taiKhoan.getText().equals("")) {
                lb_thongbao.setText("Vui lòng nhập tài khoản");
                txt_taiKhoan.requestFocus();
            } else if (String.valueOf(txt_matKhau.getPassword()).equals("")) {
                lb_thongbao.setText("Vui lòng nhập mật khẩu");
                txt_matKhau.requestFocus();
            } else {
                AccountModel A = new AccountModel(tk);
                if(danhsach.contains(A)){
                    if(tk.equals(danhsach.get(danhsach.indexOf(A)).getUsername()) && mk.equals(danhsach.get(danhsach.indexOf(A)).getPassword())){
                        lb_thongbao.setText("Thành công");
                        Main f = new Main(tk);
                        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        f.setLocationRelativeTo(null);
                        f.setResizable(false);
                        f.setVisible(true);
                        this.dispose();
                    }else {
                        lb_thongbao.setText("Sai mật khẩu");
                    }
                 
                }else{
                    lb_thongbao.setText("Sai thông tin đăng nhập");
                }

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi Đăng Nhập", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_thongbao;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_taiKhoan;
    // End of variables declaration//GEN-END:variables
}
