/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Ban_NhanSuController;
import controller.Luong_NhanSuController;
import controller.NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ban_NhanSuModel;
import model.Luong_NhanSuModel;
import model.NhanSuModel;

/**
 *
 * @author .K
 */
public class QuanLyThongTinNhanSu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyThongTinNhanSu
     */
    ArrayList<NhanSuModel> danhsach = new ArrayList<>();
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;

    public QuanLyThongTinNhanSu(String id) throws IOException {
        this.id = id;
        initComponents();
        try {
            danhsach = NhanSuController.ReadToFile();
        } catch (IOException ex) {

        }
        model = (DefaultTableModel) DSNS.getModel();
        showresult();
    }
    int t = 1;

    public void showresult() {
        for (NhanSuModel s : danhsach) {

            model.addRow(new Object[]{
                t++, s.getMaNS(), s.getHoTen(), s.getChucVu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSNS = new javax.swing.JTable();
        btn_xem = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_troVe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Quản Lý Thông Tin Nhân Sự");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        DSNS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NS", "Họ Tên", "Chức Vụ"
            }
        ));
        DSNS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSNSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DSNS);
        if (DSNS.getColumnModel().getColumnCount() > 0) {
            DSNS.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 140, 620, 220));

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 110, 34));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, 34));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 110, 34));

        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 110, 34));

        btn_troVe.setText("Trở về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_troVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DSNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSNSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DSNSMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        ThemNhanSu f = new ThemNhanSu(id);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhân sự muốn sửa!");
            }
            String t = (String) model.getValueAt(index, 1);
            SuaThongTinNhanSu f = new SuaThongTinNhanSu(id, t);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhân sự muốn xem!");
            }
            String t = (String) model.getValueAt(index, 1);
            ChiTietNhanSu f = new ChiTietNhanSu(id, t,"QLTTNS");
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_xemActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhân sự muốn xoá!");
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xoá người này?", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                ArrayList<Ban_NhanSuModel> dsBan = Ban_NhanSuController.ReadToFile();
                ArrayList<Ban_NhanSuModel> dsBanCuaNs = Ban_NhanSuController.TimBanTheoNhanSu(dsBan, danhsach.get(index));
               
                for(Ban_NhanSuModel b : dsBanCuaNs){
                    dsBan.remove(b);
                }
                ArrayList<Luong_NhanSuModel> dsLuong = Luong_NhanSuController.ReadToFile();
                ArrayList<Luong_NhanSuModel> dsLuongCuaNs = Luong_NhanSuController.TimLuongTheoNhanSu(dsLuong, danhsach.get(index));
                for(Luong_NhanSuModel b : dsLuongCuaNs){
                    dsLuong.remove(b);
                }
                danhsach.remove(index);
                Ban_NhanSuController.WriteToFile(dsBan);
                Luong_NhanSuController.WriteToFile(dsLuong);
                NhanSuController.WriteToFile(danhsach);
                QuanLyThongTinNhanSu f = new QuanLyThongTinNhanSu(id);
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        Main f;
        try {
            f = new Main(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ChiTietTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_troVeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSNS;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JButton btn_xem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
