/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LuongController;
import controller.Luong_NhanSuController;
import controller.NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.LuongModel;
import model.Luong_NhanSuModel;
import model.NhanSuModel;

/**
 *
 * @author .K
 */
public final class QuanLyLuong extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyLuong
     */
    ArrayList<NhanSuModel> listNS = new ArrayList<>();
    ArrayList<Luong_NhanSuModel> listLNS = new ArrayList<>();
    ArrayList<Luong_NhanSuModel> listLNSHienThi = new ArrayList<>();

    ArrayList<LuongModel> listL = new ArrayList<>();
    DefaultTableModel model;
    String id;

    public QuanLyLuong(String id) throws IOException {
        this.id = id;
        initComponents();
        try {
            listNS = NhanSuController.ReadToFile();
            listL = LuongController.danh_sach_L();
            listLNS = Luong_NhanSuController.ReadToFile();
        } catch (IOException ex) {

        }
        for (LuongModel p : listL) {
            jcb_LoaiNhanSu.addItem(p.getLoaiNS());
        }
        jcb_LoaiNhanSu.addItem("Xem tất cả");
        jcb_LoaiNhanSu.setSelectedIndex(listL.size());
        listLNSHienThi.clear();
        listLNSHienThi.addAll(listLNS);
        showresult();
    }

    public void showresult() {
        model = (DefaultTableModel) DSNS.getModel();
        model.setRowCount(0);
        int dem = 1;
        for (Luong_NhanSuModel s : listLNSHienThi) {
            model.addRow(new Object[]{
                dem++, s.getNhanSu().getMaNS(), s.getNhanSu().getHoTen(), s.getLuong().getLoaiNS(), String.format("%.2f", s.getLuong().TinhLuong())
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_troVe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSNS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_xem = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcb_LoaiNhanSu = new javax.swing.JComboBox<>();
        btn_xemLNS = new javax.swing.JButton();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_troVe.setText("Trở về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_troVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 90, -1));

        DSNS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NS", "Họ Tên", "Loại Viên Chức", "Lương (nghìn VND)"
            }
        ));
        DSNS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSNSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DSNS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 620, 220));

        jLabel2.setText("Quản Lý Lương");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btn_xem.setText("Xem");
        btn_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 34));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 34));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 110, 34));

        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 110, 34));

        jLabel3.setText("Loại NS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 60, 20));

        jcb_LoaiNhanSu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_LoaiNhanSuItemStateChanged(evt);
            }
        });
        jcb_LoaiNhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_LoaiNhanSuMouseClicked(evt);
            }
        });
        jcb_LoaiNhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_LoaiNhanSuActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_LoaiNhanSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 140, -1));

        btn_xemLNS.setText("Xem Loại Nhân Sự");
        btn_xemLNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemLNSActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xemLNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 140, -1));

        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        Main f;
        try {
            f = new Main(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void DSNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSNSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DSNSMouseClicked

    private void btn_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhân sự muốn xem!");
            }

            ChiTietNhanSu f = new ChiTietNhanSu(id, listLNSHienThi.get(index).getNhanSu().getMaNS(),"QLL");
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_xemActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
ThemLuongNhanVien f;
        try {
            f = new ThemLuongNhanVien(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
 try {
            if (DSNS.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Chua chon nhan su");
            } else {
                int a = DSNS.getSelectedRow();
                SuaLuongNhanVien f = new SuaLuongNhanVien(id, listLNSHienThi.get(a), null);
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(XemNhanSuTrongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
try {
            int index = DSNS.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhanSu muốn xoá!");
            }
            Luong_NhanSuModel nhanSuMuonXoa = listLNSHienThi.get(index);
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá nhan su khoi ban ? \n"
                    + nhanSuMuonXoa.getNhanSu().getHoTen()
                    + "\nLuong: " + nhanSuMuonXoa.getLuong().getLoaiNS() + "\n", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
                listLNS.remove(listLNSHienThi.get(index));
                listLNSHienThi.remove(listLNSHienThi.get(index));
                Luong_NhanSuController.WriteToFile(listLNS);
                showresult();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Xoa thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void jcb_LoaiNhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_LoaiNhanSuActionPerformed

    }//GEN-LAST:event_jcb_LoaiNhanSuActionPerformed

    private void jcb_LoaiNhanSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_LoaiNhanSuMouseClicked

    }//GEN-LAST:event_jcb_LoaiNhanSuMouseClicked

    private void jcb_LoaiNhanSuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_LoaiNhanSuItemStateChanged
        try {
            int viTriLoaiNS = jcb_LoaiNhanSu.getSelectedIndex();
            if (viTriLoaiNS < 0 || viTriLoaiNS > listL.size()) {
                throw new IOException("Khong tim thay muc luong phu hop");
            }
            listLNSHienThi.clear();
            if (viTriLoaiNS != listL.size()) {
                for (Luong_NhanSuModel ns : listLNS) {
                    if (ns.getLuong().getLoaiNS().equals(listL.get(viTriLoaiNS).getLoaiNS())) {
                        listLNSHienThi.add(ns);
                    }
                }
            } else {
                listLNSHienThi.addAll(listLNS);
            }
            showresult();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Hien thi thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jcb_LoaiNhanSuItemStateChanged

    private void btn_xemLNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemLNSActionPerformed
        XemLoaiNS f;
        try {
            f = new XemLoaiNS(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_xemLNSActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSNS;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JButton btn_xem;
    private javax.swing.JButton btn_xemLNS;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_LoaiNhanSu;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables
}
