/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TaiKhoanController;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.AccountModel;

/**
 *
 * @author .K
 */
public class SuaMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form SuaMatKhau
     */
    String id;
    ArrayList<AccountModel> listAc = new ArrayList<>();
    public SuaMatKhau(String id) throws IOException {
        this.id = id;
        listAc = TaiKhoanController.danh_sach_TK();
        initComponents();
        khoitao(listAc);
    }

    public void khoitao(ArrayList<AccountModel> list) throws IOException {
        AccountModel accountModel = new AccountModel(id);
        accountModel = list.get(list.indexOf(accountModel));
        txt_tenTK.setText("Đổi mật khẩu cho:  " + accountModel.getTen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txt_xacNhan = new javax.swing.JPasswordField();
        txt_tenTK = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_doiMK = new javax.swing.JButton();
        btn_troVe = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_matKhauCu = new javax.swing.JPasswordField();
        txt_matKhauMoi = new javax.swing.JPasswordField();
        layout = new javax.swing.JLabel();
        layout1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Xác Nhận Mật Khẩu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 26));
        getContentPane().add(txt_xacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 180, 26));
        getContentPane().add(txt_tenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 350, 26));

        jLabel3.setText("Mật Khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 91, 26));

        btn_doiMK.setText("Đổi Mật Khẩu");
        btn_doiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMKActionPerformed(evt);
            }
        });
        getContentPane().add(btn_doiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, -1));

        btn_troVe.setText("Trở Về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_troVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, -1));

        jLabel4.setText("Mật Khẩu Mới");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 91, 26));
        getContentPane().add(txt_matKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, 26));
        getContentPane().add(txt_matKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 26));

        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        layout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(layout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        try {
            ChiTietTaiKhoan f;
            f = new ChiTietTaiKhoan(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void btn_doiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMKActionPerformed
        ArrayList<AccountModel> listAc = new ArrayList<>();
        String mkc = txt_matKhauCu.getText();
        String mkm = txt_matKhauMoi.getText();
        String mkxc = txt_xacNhan.getText();
        try {
            listAc = TaiKhoanController.danh_sach_TK();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(SuaMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        AccountModel accountModel = new AccountModel(id);
        accountModel = listAc.get(listAc.indexOf(accountModel));
        try {
            if (mkc.equals("")) {
                txt_matKhauCu.requestFocus();
                throw new Exception("Mật khẩu không được để trống!");
            }
            if (mkm.equals("")) {
                txt_matKhauMoi.requestFocus();
                throw new Exception("Mật khẩu mới không được để trống!");
            }
            if (mkxc.equals("")) {
                txt_xacNhan.requestFocus();
                throw new Exception("Mật khẩu xác nhận không được để trống!");
            }
            if (mkc.equals(accountModel.getPassword())) {
                String pattern = "(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}";
                if (mkm.equals(mkxc)) {
                    if (mkm.matches(pattern)) {
                        accountModel.setPassword(mkm);
                        try {
                            TaiKhoanController.WriteToFile(listAc);
                            throw new Exception("Đổi mật khẩu thành công");
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo", JOptionPane.NO_OPTION);
                        }
                        try {
                            ChiTietTaiKhoan f;
                            f = new ChiTietTaiKhoan(id);
                            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                            f.setLocationRelativeTo(null);
                            f.setResizable(false);
                            f.setVisible(true);
                            this.dispose();
                        } catch (IOException ex) {
                            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        }
                    } else {
                        txt_matKhauMoi.requestFocus();
                        throw new Exception("Mật khẩu phải bao gồm cả chữ hoa, chữ thường, số và ít nhất 8 ký tự");
                    }
                } else {
                    txt_xacNhan.requestFocus();
                    throw new Exception("Mật khẩu không trùng nhau");
                }
            } else {
                txt_matKhauCu.requestFocus();
                throw new Exception("Sai mật khẩu");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Mật khẩu không đúng định dạng", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_doiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doiMK;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel layout;
    private javax.swing.JLabel layout1;
    private javax.swing.JPasswordField txt_matKhauCu;
    private javax.swing.JPasswordField txt_matKhauMoi;
    private javax.swing.JLabel txt_tenTK;
    private javax.swing.JPasswordField txt_xacNhan;
    // End of variables declaration//GEN-END:variables
}
