/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Ban_NhanSuController;
import controller.BanController;
import controller.NhanSuController;
import controller.PhongController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ban_NhanSuModel;
import model.BanModel;
import model.NhanSuModel;
import model.PhongModel;

/**
 *
 * @author admin
 */
public class SuaNhanSuVaoBan extends javax.swing.JFrame {

    ArrayList<PhongModel> dsPhong = new ArrayList<>();
    ArrayList<BanModel> dsBan = new ArrayList<>();
    ArrayList<BanModel> dsBanThuocPhong = new ArrayList<>();
    ArrayList<Ban_NhanSuModel> dsBan_NhanSu = new ArrayList<>();
    ArrayList<NhanSuModel> dsNhanSu = new ArrayList<>();
    ArrayList<NhanSuModel> dsNhanSu_Loc = new ArrayList<>();
    NhanSuModel nhanSuDuocChon = null;
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;
    int traVe;
    BanModel thuocBan, banModel;
    Ban_NhanSuModel nhanSuSua;

    public SuaNhanSuVaoBan(String id, BanModel banModel, Ban_NhanSuModel nhanSuSua, int traVe) throws IOException {
        initComponents();
        this.id = id;
        this.banModel = banModel;
        this.nhanSuSua = nhanSuSua;
        this.thuocBan = nhanSuSua.getBan();
        this.nhanSuDuocChon = nhanSuSua.getNhanSu();
        this.traVe = traVe;
        try {
            dsPhong = PhongController.ReadToFile();
            dsBan = BanController.ReadToFile();
            dsBan_NhanSu = Ban_NhanSuController.ReadToFile();
            dsNhanSu = NhanSuController.ReadToFile();
            dsNhanSu_Loc.addAll(dsNhanSu);

        } catch (IOException ex) {
            System.out.println("Loi");
        }

        txt_NhanSu.setText(nhanSuDuocChon.getMaNS() + " - " + nhanSuDuocChon.getHoTen() + " - " + nhanSuDuocChon.getChuyenNganh());
        txt_ChucVu.setText(nhanSuSua.getChucVu());

        for (PhongModel p : dsPhong) {
            cbbox_dsPhong.addItem(p.getMaPhong() + " - " + p.getTenPhong());
        }
//        for (BanModel b : dsBan) {
//            cbbox_dsBan.addItem(b.getMaBan() + " - " + b.getTenBan());
//        }

        if (thuocBan.getMaBan().equals("")) {
            if (thuocBan.getThuocPhong() == null) {
                cbbox_dsPhong.setSelectedIndex(0);
                dsBanThuocPhong = BanController.TimBanTheoPhong(dsBan, dsPhong.get(0));
                cbbox_dsBan.removeAllItems();
                for (BanModel b : dsBanThuocPhong) {
                    cbbox_dsBan.addItem(b.getMaBan() + " - " + b.getTenBan());
                }
            } else {
                cbbox_dsPhong.setSelectedIndex(dsPhong.indexOf(thuocBan.getThuocPhong()));
                dsBanThuocPhong = BanController.TimBanTheoPhong(dsBan, thuocBan.getThuocPhong());
                cbbox_dsBan.removeAllItems();
                for (BanModel b : dsBanThuocPhong) {
                    cbbox_dsBan.addItem(b.getMaBan() + " - " + b.getTenBan());
                }
                cbbox_dsBan.setSelectedIndex(0);
            }

        } else {
            cbbox_dsPhong.setSelectedIndex(dsPhong.indexOf(thuocBan.getThuocPhong()));
            dsBanThuocPhong = BanController.TimBanTheoPhong(dsBan, thuocBan.getThuocPhong());
            cbbox_dsBan.removeAllItems();
            for (BanModel b : dsBanThuocPhong) {
                cbbox_dsBan.addItem(b.getMaBan() + " - " + b.getTenBan());
            }
            cbbox_dsBan.setSelectedIndex(dsBanThuocPhong.indexOf(thuocBan));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable_thongBaoLoi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_ChucVu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_NhanSu = new javax.swing.JTextField();
        cbbox_dsPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbbox_dsBan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lable_thongBaoLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 30));
        getContentPane().add(txt_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 310, 30));

        jLabel2.setText("Chức vụ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel3.setText("Phòng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txt_NhanSu.setEnabled(false);
        txt_NhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhanSuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NhanSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 310, 30));

        cbbox_dsPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_dsPhongActionPerformed(evt);
            }
        });
        getContentPane().add(cbbox_dsPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 310, 30));

        jLabel4.setText("Nhân viên");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cbbox_dsBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_dsBanActionPerformed(evt);
            }
        });
        getContentPane().add(cbbox_dsBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 310, 30));

        jLabel5.setText("Ban");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (nhanSuDuocChon == null) {
                throw new IOException("Chua chon nhan su");
            }
            if (cbbox_dsPhong.getSelectedIndex() < 0) {
                throw new IOException("Chua chon phong");
            }
            if (cbbox_dsBan.getSelectedIndex() < 0) {
                throw new IOException("Chua chon ban");
            }
            if (txt_ChucVu.getText().equals("")) {
                throw new IOException("Chuc vu khong duoc de trong");
            }
            Ban_NhanSuModel newBan_NhanSu = new Ban_NhanSuModel(nhanSuDuocChon, dsBanThuocPhong.get(cbbox_dsBan.getSelectedIndex()), txt_ChucVu.getText());
            ArrayList<Ban_NhanSuModel> dsBanNhanSuCheck = new ArrayList<>();
            dsBanNhanSuCheck.addAll(dsBan_NhanSu);
            dsBanNhanSuCheck.remove(nhanSuSua);
            if (dsBanNhanSuCheck.contains(newBan_NhanSu) == true) {
                throw new IOException("Nhân s? dã ? trong ban!");
            }
            if (newBan_NhanSu.getChucVu().compareToIgnoreCase("Trưởng phòng") == 0 || newBan_NhanSu.getChucVu().compareToIgnoreCase("Trưởng ban") == 0) {
                for (BanModel ban : dsBanThuocPhong) {
                    for (Ban_NhanSuModel ban_NhanSu : Ban_NhanSuController.TimNhanSuTheoBan(dsBan_NhanSu, ban)) {
                        if (!ban_NhanSu.equals(nhanSuSua)) {
                            if (ban_NhanSu.getChucVu().compareToIgnoreCase("Trưởng phòng") == 0 && newBan_NhanSu.getChucVu().compareToIgnoreCase("Trưởng phòng") == 0) {
                                throw new IOException("Phòng " + ban.getThuocPhong().getTenPhong() + " dã có tru?ng phòng!");
                            }
                            if (ban.equal(newBan_NhanSu.getBan()) && ban_NhanSu.getChucVu().compareToIgnoreCase("Trưởng ban") == 0 && newBan_NhanSu.getChucVu().compareToIgnoreCase("Trưởng ban") == 0) {
                                throw new IOException("Ban " + ban.getTenBan() + " dã có tru?ng ban!");
                            }
                        }

                    }
                }
            }
            int viTri = dsBan_NhanSu.indexOf(nhanSuSua);
            dsBan_NhanSu.remove(nhanSuSua);
            dsBan_NhanSu.add(viTri, newBan_NhanSu);
            Ban_NhanSuController.WriteToFile(dsBan_NhanSu);
            try {
                XemNhanSuTrongBan f;
                if (traVe == 0) {
                    f = new XemNhanSuTrongBan(id, banModel, null);
                } else {
                    f = new XemNhanSuTrongBan(id, null, nhanSuDuocChon);
                }
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thêm thất bại!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbox_dsPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_dsPhongActionPerformed

        dsBanThuocPhong = BanController.TimBanTheoPhong(dsBan, dsPhong.get(cbbox_dsPhong.getSelectedIndex()));
        cbbox_dsBan.removeAllItems();
        for (BanModel b : dsBanThuocPhong) {
            cbbox_dsBan.addItem(b.getMaBan() + " - " + b.getTenBan());
        }
    }//GEN-LAST:event_cbbox_dsPhongActionPerformed

    private void cbbox_dsBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_dsBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbox_dsBanActionPerformed

    private void txt_NhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhanSuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NhanSuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            XemNhanSuTrongBan f;
            if (traVe == 0) {
                f = new XemNhanSuTrongBan(id, banModel, null);
            } else {
                f = new XemNhanSuTrongBan(id, new BanModel("", "", null), nhanSuDuocChon);
            }
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbox_dsBan;
    private javax.swing.JComboBox<String> cbbox_dsPhong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lable_thongBaoLoi;
    private javax.swing.JTextField txt_ChucVu;
    private javax.swing.JTextField txt_NhanSu;
    // End of variables declaration//GEN-END:variables
}
