/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BanController;
import controller.PhongController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.BanModel;
import model.PhongModel;

/**
 *
 * @author admin
 */
public class SuaPhong extends javax.swing.JFrame {

    ArrayList<PhongModel> dsPhong = new ArrayList<>();
    java.awt.Frame bb;
    int viTriPhong;
    PhongModel newPhong;
    String id;

    public SuaPhong(String id, int viTri) throws IOException {
        initComponents();
        this.id = id;
        viTriPhong = viTri;

        try {
            dsPhong = PhongController.ReadToFile();
            newPhong = dsPhong.get(viTriPhong);
        } catch (IOException e) {

        }
        showResult();
    }

    public void showResult() {
        txt_MaPhongMoi.setText(newPhong.getMaPhong());
        txt_TenPhongMoi.setText(newPhong.getTenPhong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable_thongBaoLoi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_TenPhongMoi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_MaPhongMoi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lable_thongBaoLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jButton1.setText("Thêm phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 30));
        getContentPane().add(txt_TenPhongMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 210, 30));

        jLabel2.setText("Tên phòng mới");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 185, -1, -1));

        jLabel3.setText("Mã phòng mới");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 145, -1, -1));
        getContentPane().add(txt_MaPhongMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 210, 30));

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<PhongModel> dsPhongCheck = new ArrayList<>();
        dsPhongCheck.addAll(dsPhong);
        try {
            if (txt_TenPhongMoi.getText().compareTo("") == 0 || txt_MaPhongMoi.getText().compareTo("") == 0) {
                throw new IOException("Tên phòng và mã phòng không duoc de trong");
            } else {
                dsPhongCheck.remove(dsPhong.get(viTriPhong));
                newPhong = new PhongModel(txt_MaPhongMoi.getText(), txt_TenPhongMoi.getText());
                if (dsPhongCheck.contains(newPhong) == true) {
                    throw new IOException("Tên phòng ho?c mã phòng dã có");
                } else {
                    ArrayList<BanModel> list = BanController.ReadToFile();
                    for (BanModel bx : list) {
                        if (bx.getThuocPhong().equals(dsPhong.get(viTriPhong))) {
                            bx.setThuocPhong(newPhong);
                        }
                    }
                    BanController.WriteToFile(list);
                    dsPhong.remove(dsPhong.get(viTriPhong));
                    dsPhong.add(viTriPhong, newPhong);
                    BanController.SuaBanTheoPhong(dsPhong.get(viTriPhong), newPhong);
                    PhongController.WriteToFile(dsPhong);
                    try {
                        XemPhong f = new XemPhong(id);
                        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        f.setLocationRelativeTo(null);
                        f.setResizable(false);
                        f.setVisible(true);
                        this.dispose();
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Sửa thông tin phòng thất bại!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            XemPhong f = new XemPhong(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lable_thongBaoLoi;
    private javax.swing.JTextField txt_MaPhongMoi;
    private javax.swing.JTextField txt_TenPhongMoi;
    // End of variables declaration//GEN-END:variables
}
