/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TuyenDungController;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.NhanSuModel;
import model.TuyenDungModel;

/**
 *
 * @author vmass
 */
public class SuaThongTinUngVien extends javax.swing.JFrame {

    ArrayList<TuyenDungModel> danhsachtd = new ArrayList<>();
    String id;
    /**
     * Creates new form ThemNhanSu
     */
    public SuaThongTinUngVien(String id,String maTD) {
        this.id = id;
        initComponents();
        try {
            danhsachtd = TuyenDungController.ReadToFileTD();
        } catch (IOException ex) {
        }
        showresult(maTD);
    }

    private SuaThongTinUngVien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void showresult(String MaTD){
        TuyenDungModel s = new TuyenDungModel(MaTD);
        if (danhsachtd.contains(s)) {
            TuyenDungModel ns = danhsachtd.get(danhsachtd.indexOf(s));
            txt_mTD.setText(ns.getMaTD());
            txt_hoTen.setText(ns.getHoTen());
            txt_ngaySinh.setText(ns.getNgaySinh());
            if (ns.isGioiTinh()) {
                gioitinh_nam.isSelected();
            } else {
                gioitinh_nu.isSelected();
            }
            txt_chucVu.setSelectedItem(ns.getViTriTd());
            txt_queQuan.setText(ns.getQueQuan());
            txt_cCCD.setText(ns.getCCCD());
            txt_soDT.setText(ns.getSoDT());
            txt_danToc.setText(ns.getDanToc());
            txt_trinhDo.setText(ns.getTrinhDo());
            txt_chuyenNganh.setText(ns.getChuyenNganh());
            txt_ngayNopDon.setText(ns.getNgayNopDon());
            txt_tinhTrang.setText(ns.getTrangThai());
            danhsachtd.remove(ns);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txt_mTD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cCCD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_queQuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_danToc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_trinhDo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_ngayNopDon = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_chuyenNganh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tinhTrang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_soDT = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        txt_chucVu = new javax.swing.JComboBox<>();
        gioitinh_nam = new javax.swing.JRadioButton();
        gioitinh_nu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã Tuyen Dung");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 97, -1));
        getContentPane().add(txt_mTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 99, -1));

        jLabel3.setText("Họ Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 97, -1));
        getContentPane().add(txt_hoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 99, -1));

        jLabel4.setText("Số CCCD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 97, -1));
        getContentPane().add(txt_cCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 99, -1));

        jLabel5.setText("Ngày Sinh");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 97, -1));
        getContentPane().add(txt_ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 99, -1));

        jLabel6.setText("Quê Quán");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 97, -1));
        getContentPane().add(txt_queQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 99, -1));

        jLabel7.setText("Giới Tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 97, -1));

        jLabel8.setText("Dân Tộc");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 97, -1));
        getContentPane().add(txt_danToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 99, -1));

        jLabel10.setText("Chức Vụ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 97, -1));

        jLabel11.setText("Trình Độ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 97, -1));
        getContentPane().add(txt_trinhDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 99, -1));

        jLabel12.setText("Ngày Nop Don");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 97, -1));
        getContentPane().add(txt_ngayNopDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 99, -1));

        jLabel14.setText("Chuyên Ngành");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 97, -1));
        getContentPane().add(txt_chuyenNganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 99, -1));

        jLabel15.setText("Tinh Trang");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 97, -1));
        getContentPane().add(txt_tinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 99, -1));

        jLabel16.setText("Số Điện Thoại");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 97, -1));
        getContentPane().add(txt_soDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 99, -1));

        btn_them.setText("Sua");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        btn_huy.setText("Huỷ");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        txt_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảng Viên", "Bảo Vệ", "Lao Công" }));
        txt_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chucVuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_chucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 100, -1));

        gioitinh_nam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(gioitinh_nam);
        gioitinh_nam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gioitinh_nam.setSelected(true);
        gioitinh_nam.setText("Nam");
        gioitinh_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioitinh_namActionPerformed(evt);
            }
        });
        getContentPane().add(gioitinh_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        gioitinh_nu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(gioitinh_nu);
        gioitinh_nu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gioitinh_nu.setText("Nữ");
        getContentPane().add(gioitinh_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try{
            if(txt_mTD.getText().equals("")){
                txt_mTD.requestFocus();
                throw new Exception("Mã nhân sự không được để trống!");
            }
            if(txt_hoTen.getText().equals("")){
                txt_hoTen.requestFocus();
                throw new Exception("Họ tên không được để trống!");
            }
            if(txt_cCCD.getText().equals("")){
                txt_cCCD.requestFocus();
                throw new Exception("Số căn cước không được để trống!");
            }
            if(!txt_cCCD.getText().matches("[0-9]+")){
                txt_cCCD.requestFocus();
                throw new Exception("Số căn cước chỉ bao gồm số!");
            }
            if(txt_ngaySinh.getText()==null)
            throw new Exception("Ngày sinh không được để trống!");
            if(txt_queQuan.getText().equals("")){
                txt_queQuan.requestFocus();
                throw new Exception("Quê quán không được để trống!");
            }
            if(txt_danToc.getText().equals("")){
                txt_danToc.requestFocus();
                throw new Exception("Dân tộc không được để trống!");
            }
            if(txt_soDT.getText().equals("")){
                txt_soDT.requestFocus();
                throw new Exception("Số điện thoại không được để trống!");
            }
            if(!txt_soDT.getText().matches("[0-9]+")){
                txt_soDT.requestFocus();
                throw new Exception("Số điện thoại chỉ bao gồm số!");
            }
            if(txt_trinhDo.getText().equals("")){
                txt_trinhDo.requestFocus();
                throw new Exception("Trình độ không được để trống!");
            }
            if(txt_chuyenNganh.getText().equals("")){
                txt_chuyenNganh.requestFocus();
                throw new Exception("Chuyên ngành không được để trống!");
            }
            if(txt_ngayNopDon.getText()==null)
            throw new Exception("Ngày nop don không được để trống!");
            if(txt_tinhTrang.getText()==null)
            throw new Exception("Tinh trang không được để trống!");
            TuyenDungModel ns = new TuyenDungModel();
            ns.setMaTD(txt_mTD.getText());
            if(danhsachtd.contains(ns)){
                throw new Exception("Mã nhân sự đã tồn tại!");
            }
            ns.setHoTen(txt_hoTen.getText());
            ns.setNgaySinh(txt_ngaySinh.getText());
            ns.setGioiTinh(gioitinh_nam.isSelected()?true:false);
            ns.setQueQuan(txt_queQuan.getText());
            ns.setCCCD(txt_cCCD.getText());
            ns.setSoDT(txt_soDT.getText());
            ns.setDanToc(txt_danToc.getText());
            ns.setViTriTd((String)txt_chucVu.getSelectedItem());
            ns.setTrinhDo(txt_trinhDo.getText());
            ns.setChuyenNganh(txt_chuyenNganh.getText());
            ns.setNgayNopDon(txt_ngayNopDon.getText());
            ns.setTrangThai(txt_tinhTrang.getText());
            danhsachtd.add(ns);
            TuyenDungController.WriteToFile(danhsachtd);
            JOptionPane.showMessageDialog(this,"Thêm thành công!");
            TuyenDung f = new TuyenDung(id);
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thêm thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        try {
            TuyenDung f;
            f = new TuyenDung(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Them_Ung_Vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_huyActionPerformed

    private void txt_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chucVuActionPerformed

    private void gioitinh_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioitinh_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioitinh_namActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_them;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gioitinh_nam;
    private javax.swing.JRadioButton gioitinh_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_cCCD;
    private javax.swing.JComboBox<String> txt_chucVu;
    private javax.swing.JTextField txt_chuyenNganh;
    private javax.swing.JTextField txt_danToc;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_mTD;
    private javax.swing.JTextField txt_ngayNopDon;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_queQuan;
    private javax.swing.JTextField txt_soDT;
    private javax.swing.JTextField txt_tinhTrang;
    private javax.swing.JTextField txt_trinhDo;
    // End of variables declaration//GEN-END:variables
}
