/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LuongController;
import controller.Luong_NhanSuController;
import controller.NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Luong_NhanSuModel;
import model.LuongModel;
import model.NhanSuModel;

/**
 *
 * @author admin
 */
public class ThemLuongNhanVien extends javax.swing.JFrame {

    ArrayList<LuongModel> dsLuong = new ArrayList<>();
    ArrayList<Luong_NhanSuModel> dsLuong_NhanSu = new ArrayList<>();
    ArrayList<NhanSuModel> dsNhanSu = new ArrayList<>();
    ArrayList<NhanSuModel> dsNhanSu_Loc = new ArrayList<>();
    NhanSuModel nhanSuDuocChon = null;
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;

    public ThemLuongNhanVien(String id) throws IOException {
        initComponents();
        this.id = id;
        try {
            dsLuong = LuongController.danh_sach_L();
            dsLuong_NhanSu = Luong_NhanSuController.ReadToFile();
            dsNhanSu = NhanSuController.ReadToFile();
            dsNhanSu_Loc.addAll(dsNhanSu);

        } catch (IOException ex) {
            System.out.println("Loi");
        }

        model = (DefaultTableModel) table_NhanSu.getModel();
        hienThiDsNhanSu();

        for (LuongModel b : dsLuong) {
            cbbox_dsLuong.addItem(b.getLoaiNS());
        }
    }

    public void hienThiDsNhanSu() {
        model.setRowCount(0);
        for (NhanSuModel n : dsNhanSu_Loc) {
            model.addRow(new Object[]{
                n.getMaNS(), n.getHoTen(), n.getChuyenNganh()
            });
        }
    }

    public void timKiemDsNhanSu() {
        dsNhanSu_Loc.clear();

        String keywordChuyennganh = text_KeywordChuyenNganh.getText();
        String keywordTen = text_KeywordTen.getText();
        String keywordMa = text_KeywordMa.getText();

        for (NhanSuModel n : dsNhanSu) {
            if (n.getMaNS().toLowerCase().contains(keywordMa.toLowerCase())
                    && n.getHoTen().toLowerCase().contains(keywordTen.toLowerCase())
                    && n.getChuyenNganh().toLowerCase().contains(keywordChuyennganh.toLowerCase())) {
                dsNhanSu_Loc.add(n);
            }
        }
        hienThiDsNhanSu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lable_thongBaoLoi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_NhanSu = new javax.swing.JTextField();
        cbbox_dsLuong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_NhanSu = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_KeywordChuyenNganh = new javax.swing.JTextField();
        text_KeywordMa = new javax.swing.JTextField();
        text_KeywordTen = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lable_thongBaoLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 30));

        jLabel3.setText("Loại Viên chức");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txt_NhanSu.setEnabled(false);
        txt_NhanSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhanSuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NhanSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 310, 30));

        cbbox_dsLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbox_dsLuongActionPerformed(evt);
            }
        });
        getContentPane().add(cbbox_dsLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 310, 30));

        jLabel4.setText("Nhân viên");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        table_NhanSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Họ Tên", "Chuyên ngành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_NhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_NhanSuMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_NhanSu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 500, 270));

        jLabel6.setText("Tìm theo chuyên ngành");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        jLabel7.setText("Tìm kiếm theo mã");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel8.setText("Tìm kiếm theo tên");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        text_KeywordChuyenNganh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_KeywordChuyenNganhKeyReleased(evt);
            }
        });
        getContentPane().add(text_KeywordChuyenNganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 160, 30));

        text_KeywordMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_KeywordMaActionPerformed(evt);
            }
        });
        text_KeywordMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_KeywordMaKeyReleased(evt);
            }
        });
        getContentPane().add(text_KeywordMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, 30));

        text_KeywordTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_KeywordTenKeyReleased(evt);
            }
        });
        getContentPane().add(text_KeywordTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 160, 30));

        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang trang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (txt_NhanSu.getText().equals("") && nhanSuDuocChon == null) {
                throw new IOException("Chua chon nhan su");
            }
            if (cbbox_dsLuong.getSelectedIndex() < 0) {
                throw new IOException("Chua chon luong");
            }
            Luong_NhanSuModel newLuong_NhanSu = new Luong_NhanSuModel(nhanSuDuocChon, dsLuong.get(cbbox_dsLuong.getSelectedIndex()));
            if (dsLuong_NhanSu.contains(newLuong_NhanSu) == true) {
                throw new IOException("Nhân s? dã ? trong luong!");
            }

            dsLuong_NhanSu.add(newLuong_NhanSu);
            Luong_NhanSuController.WriteToFile(dsLuong_NhanSu);
            try {
                QuanLyLuong f = new QuanLyLuong(id);
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thêm thất bại!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbox_dsLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbox_dsLuongActionPerformed

    }//GEN-LAST:event_cbbox_dsLuongActionPerformed

    private void txt_NhanSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhanSuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NhanSuActionPerformed

    private void text_KeywordMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_KeywordMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_KeywordMaActionPerformed

    private void text_KeywordMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_KeywordMaKeyReleased
        timKiemDsNhanSu();
    }//GEN-LAST:event_text_KeywordMaKeyReleased

    private void text_KeywordTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_KeywordTenKeyReleased
        timKiemDsNhanSu();
    }//GEN-LAST:event_text_KeywordTenKeyReleased

    private void text_KeywordChuyenNganhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_KeywordChuyenNganhKeyReleased
        timKiemDsNhanSu();
    }//GEN-LAST:event_text_KeywordChuyenNganhKeyReleased

    private void table_NhanSuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NhanSuMousePressed
        nhanSuDuocChon = dsNhanSu_Loc.get(table_NhanSu.getSelectedRow());
        txt_NhanSu.setText(nhanSuDuocChon.getMaNS() + " - " + nhanSuDuocChon.getHoTen() + " - " + nhanSuDuocChon.getChuyenNganh());
    }//GEN-LAST:event_table_NhanSuMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            QuanLyLuong f = new QuanLyLuong(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbox_dsLuong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lable_thongBaoLoi;
    private javax.swing.JTable table_NhanSu;
    private javax.swing.JTextField text_KeywordChuyenNganh;
    private javax.swing.JTextField text_KeywordMa;
    private javax.swing.JTextField text_KeywordTen;
    private javax.swing.JTextField txt_NhanSu;
    // End of variables declaration//GEN-END:variables
}
