/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BanController;
import controller.Ban_NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.BanModel;
import model.Ban_NhanSuModel;
import model.PhongModel;

/**
 *
 * @author admin
 */
public class XemBan extends javax.swing.JFrame {
    ArrayList<BanModel> dsBan = new ArrayList<>();
    ArrayList<Ban_NhanSuModel> dsBan_NhanSu = new ArrayList<>();
    ArrayList<BanModel> dsBanThuocPhong = new ArrayList<>();
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;
    PhongModel thuocPhong;

    public XemBan(String id, PhongModel thuocPhong) throws IOException {
        initComponents();
        this.id = id;
        this.thuocPhong = thuocPhong;
        try {
            dsBan = BanController.ReadToFile();
            dsBan_NhanSu = Ban_NhanSuController.ReadToFile();
            if(thuocPhong != null){
                dsBanThuocPhong = BanController.TimBanTheoPhong(dsBan, thuocPhong);
                text_Phong.setText(text_Phong.getText() + thuocPhong.getTenPhong());
            }
            else {
                dsBanThuocPhong.addAll(dsBan);
                text_Phong.setText(text_Phong.getText() + "Tat ca phong");
            }
        } catch (IOException ex) {

        }
        model = (DefaultTableModel) tableDanhSachBan.getModel();
        showresult();
    }

    public void showresult() {
        for (BanModel s : dsBanThuocPhong) {
            model.addRow(new Object[]{
                s.getMaBan(), s.getTenBan(), Ban_NhanSuController.TimNhanSuTheoBan(dsBan_NhanSu, s).size(), s.getThuocPhong().getTenPhong()
            });
        }
    }
    public void XoaBan_NhanSuTheoBan(BanModel banXoa) {
        try {
            ArrayList<Ban_NhanSuModel> list = new ArrayList<>();
            list.addAll(dsBan_NhanSu);
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getBan().equals(banXoa)) {
                    list.remove(list.get(i));
                    i--;
                }
            }
            Ban_NhanSuController.WriteToFile(list);
        } catch (IOException e) {
            System.out.println("Loi b");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableDanhSachBan = new javax.swing.JTable();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        trove = new javax.swing.JButton();
        xemNhanSuTrongBan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        text_Phong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDanhSachBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ban", "Tên ban", "Số người trong ban ", "Thuộc phòng "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDanhSachBan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 210));

        btn_Them.setText("Thêm Ban");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 120, -1));

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        trove.setText("Thoát");
        trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troveActionPerformed(evt);
            }
        });
        getContentPane().add(trove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        xemNhanSuTrongBan.setText("Xem Ban");
        xemNhanSuTrongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemNhanSuTrongBanActionPerformed(evt);
            }
        });
        getContentPane().add(xemNhanSuTrongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jButton1.setText("Xem Tất Cả Ban Của Phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        text_Phong.setText("Phòng: ");
        getContentPane().add(text_Phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        try {
            ThemBan f = new ThemBan(id, thuocPhong);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        try {
            if (tableDanhSachBan.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Ban chua chon ban");
            } else {
                int a = tableDanhSachBan.getSelectedRow();
                SuaBan f = new SuaBan(id, thuocPhong, dsBanThuocPhong.get(tableDanhSachBan.getSelectedRow()));
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        try {
            int index = tableDanhSachBan.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn ban muốn xoá!");
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xoá ban " + dsBanThuocPhong.get(index).getTenBan() + " ?", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                BanModel banXoa = dsBanThuocPhong.get(index);
                dsBan.remove(banXoa);
                BanController.WriteToFile(dsBan);
                XoaBan_NhanSuTheoBan(banXoa);
                
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Xoa thất bại!", JOptionPane.ERROR_MESSAGE);
        }
        try {
            XemBan f = new XemBan(id, thuocPhong);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troveActionPerformed
        XemPhong f;
        try {
            f = new XemPhong(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_troveActionPerformed

    private void xemNhanSuTrongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemNhanSuTrongBanActionPerformed
        try {
            if (tableDanhSachBan.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(rootPane, "Ban chua chon ban");
            } else {
                int a = tableDanhSachBan.getSelectedRow();
                XemNhanSuTrongBan f = new XemNhanSuTrongBan(id, dsBanThuocPhong.get(tableDanhSachBan.getSelectedRow()), null);
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_xemNhanSuTrongBanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        XemNhanSuTrongBan f;
        try {
            f = new XemNhanSuTrongBan(id, new BanModel("", "", thuocPhong), null);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDanhSachBan;
    private javax.swing.JLabel text_Phong;
    private javax.swing.JButton trove;
    private javax.swing.JButton xemNhanSuTrongBan;
    // End of variables declaration//GEN-END:variables

}
