/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LuongController;
import controller.Luong_NhanSuController;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.LuongModel;
import model.Luong_NhanSuModel;

/**
 *
 * @author .K
 */
public class XemLoaiNS extends javax.swing.JFrame {

    /**
     * Creates new form XemLoaiNS
     */
    ArrayList<LuongModel> danhsach = new ArrayList<>();
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;
    public XemLoaiNS(String id)throws IOException {
        this.id = id;
        initComponents();
        try {
            danhsach = LuongController.danh_sach_L();
        } catch (IOException ex) {
            
        }
        model = (DefaultTableModel) DSNS.getModel();
        showresult();
    }
    int t=1;
    public void showresult(){
        for(LuongModel s : danhsach){
        model.addRow(new Object[]{
            t++,s.getLoaiNS(),s.getmLCS(),s.getHSL(),s.getPhuCap(),s.getBaohiem()
        });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_troVe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSNS = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_troVe.setText("Thoát ");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_troVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, -1));

        jLabel2.setText("Quản Lý Lương");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        DSNS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Loại NS", "Hệ Số Lương", "Lương Cơ Sở", "Phụ Cấp", "Bảo Hiểm"
            }
        ));
        DSNS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSNSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DSNS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 140, 620, 220));

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, 34));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 110, 34));

        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 110, 34));

        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        QuanLyLuong f;
        try {
            f = new QuanLyLuong(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void DSNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSNSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DSNSMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        ThemLoaiNS f;
        f = new ThemLoaiNS(id);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if(index==-1){
                throw new IOException("Bạn chưa chọn Loại NS muốn xoá!");
            }
            SuaLoaiNS f = new SuaLoaiNS(id,danhsach.get(index));
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) { 
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            int index = DSNS.getSelectedRow();
            if(index==-1){
                throw new IOException("Bạn chưa chọn Loại NS muốn xoá!");
            }
            ArrayList<Luong_NhanSuModel> dsNhanSu = Luong_NhanSuController.ReadToFile();
            ArrayList<Luong_NhanSuModel> luong_NhanSuXoa = Luong_NhanSuController.TimNhanSuTheoLuong(dsNhanSu, danhsach.get(index));
            if(JOptionPane.showConfirmDialog (null, "Bạn có chắc muốn xoá "+ danhsach.get(index).getLoaiNS() + " \n"
                                                    + "Ðông thoi xóa " + luong_NhanSuXoa.size() + " du lieu luong nhan su","Cảnh báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            dsNhanSu.removeAll(luong_NhanSuXoa);
            Luong_NhanSuController.WriteToFile(dsNhanSu);
            
            danhsach.remove(index);
            LuongController.WriteToFile(danhsach);
            XemLoaiNS f = new XemLoaiNS(id);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
            }
        } catch (IOException ex) { 
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSNS;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables
}
