/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BanController;
import controller.Ban_NhanSuController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.Ban_NhanSuModel;
import model.BanModel;
import model.NhanSuModel;

/**
 *
 * @author admin
 */
public class XemNhanSuTrongBan extends javax.swing.JFrame {

    ArrayList<Ban_NhanSuModel> dsBan_NhanSu = new ArrayList<>();
    ArrayList<Ban_NhanSuModel> dsBan_NhanSuThuocBan = new ArrayList<>();
    DefaultTableModel model;
    java.awt.Frame bb;
    String id;
    BanModel thuocBan;
    NhanSuModel nhanSu;

    public XemNhanSuTrongBan(String id, BanModel thuocBan, NhanSuModel nhanSu) throws IOException {
        initComponents();
        this.id = id;
        this.thuocBan = thuocBan;
        this.nhanSu = nhanSu;
        try {
            dsBan_NhanSu = Ban_NhanSuController.ReadToFile();
            if (nhanSu == null) {
                if (!thuocBan.getMaBan().equals("")) {
                    dsBan_NhanSuThuocBan = Ban_NhanSuController.TimNhanSuTheoBan(dsBan_NhanSu, thuocBan);
                    text_Ban.setText(text_Ban.getText() + thuocBan.getTenBan());
                    text_Phong.setText(text_Phong.getText() + thuocBan.getThuocPhong().getTenPhong());
                } else if (thuocBan.getThuocPhong() != null) {
                    ArrayList<BanModel> dsBanThuocPhong = BanController.TimBanTheoPhong(BanController.ReadToFile(), thuocBan.getThuocPhong());
                    for (BanModel b : dsBanThuocPhong) {
                        dsBan_NhanSuThuocBan.addAll(Ban_NhanSuController.TimNhanSuTheoBan(dsBan_NhanSu, b));
                    }
                    text_Ban.setText(text_Ban.getText() + "Tat ca ban");
                    text_Phong.setText(text_Phong.getText() + thuocBan.getThuocPhong().getTenPhong());
                } else {
                    dsBan_NhanSuThuocBan.addAll(dsBan_NhanSu);
                    text_Ban.setText(text_Ban.getText() + "Tat ca ban");
                    text_Phong.setText(text_Phong.getText() + "Tat ca phong");
                }
            } else {
                dsBan_NhanSuThuocBan = Ban_NhanSuController.TimBanTheoNhanSu(dsBan_NhanSu, nhanSu);
                text_Ban.setText(text_Ban.getText() + "Tat ca ban");
                text_Phong.setText(text_Phong.getText() + "Tat ca phong");
            }
        } catch (IOException ex) {

        }
        model = (DefaultTableModel) tableDanhSachNhanSu.getModel();
        showresult();
    }

    public void showresult() {
        for (Ban_NhanSuModel s : dsBan_NhanSuThuocBan) {
            model.addRow(new Object[]{
                s.getBan().getThuocPhong().getTenPhong(),
                s.getBan().getTenBan(),
                s.getNhanSu().getHoTen(),
                s.getNhanSu().getChuyenNganh(),
                s.getChucVu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableDanhSachNhanSu = new javax.swing.JTable();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        trove = new javax.swing.JButton();
        xemNhanSuTrongBan = new javax.swing.JButton();
        text_Phong = new javax.swing.JLabel();
        text_Ban = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDanhSachNhanSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phòng", "Ban", "Mã nhân sự", "Tên nhân sự", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDanhSachNhanSu);
        if (tableDanhSachNhanSu.getColumnModel().getColumnCount() > 0) {
            tableDanhSachNhanSu.getColumnModel().getColumn(1).setResizable(false);
            tableDanhSachNhanSu.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 590, 190));

        btn_Them.setText("Thêm nhân sự");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, -1));

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        trove.setText("Thoát");
        trove.setToolTipText("");
        trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troveActionPerformed(evt);
            }
        });
        getContentPane().add(trove, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        xemNhanSuTrongBan.setText("Xem thông tin nhân sự");
        xemNhanSuTrongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemNhanSuTrongBanActionPerformed(evt);
            }
        });
        getContentPane().add(xemNhanSuTrongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        text_Phong.setText("Phòng: ");
        getContentPane().add(text_Phong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        text_Ban.setText("Ban: ");
        getContentPane().add(text_Ban, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/man ngang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        try {
            ThemNhanSuVaoBan f = new ThemNhanSuVaoBan(id, thuocBan, nhanSu);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemNhanSuTrongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        try {
            if (tableDanhSachNhanSu.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(rootPane, "NhanSu chua chon nhanSu");
            } else {
                int a = tableDanhSachNhanSu.getSelectedRow();
                SuaNhanSuVaoBan f;
                if (this.nhanSu == null) {
                    f = new SuaNhanSuVaoBan(id,thuocBan, dsBan_NhanSuThuocBan.get(tableDanhSachNhanSu.getSelectedRow()), 0);
                } else {
                    f = new SuaNhanSuVaoBan(id,thuocBan, dsBan_NhanSuThuocBan.get(tableDanhSachNhanSu.getSelectedRow()), 1);
                }
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(XemNhanSuTrongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        try {
            int index = tableDanhSachNhanSu.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhanSu muốn xoá!");
            }
            Ban_NhanSuModel nhanSuMuonXoa = dsBan_NhanSuThuocBan.get(index);
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá nhan su khoi ban ? \n"
                    + nhanSuMuonXoa.getNhanSu().getHoTen()
                    + "\nBan: " + nhanSuMuonXoa.getBan().getTenBan()
                    + "\nChuc vu: " + nhanSuMuonXoa.getChucVu() + "\n", "Cảnh báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
                dsBan_NhanSu.remove(dsBan_NhanSuThuocBan.get(index));
                Ban_NhanSuController.WriteToFile(dsBan_NhanSu);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Xoa thất bại!", JOptionPane.ERROR_MESSAGE);
        }
        try {
            XemNhanSuTrongBan f = new XemNhanSuTrongBan(id, thuocBan, nhanSu);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(XemNhanSuTrongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troveActionPerformed

        try {
            if (nhanSu == null) {
                XemBan f = new XemBan(id, thuocBan.getThuocPhong());
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            } else {
                ChiTietNhanSu f = new ChiTietNhanSu(id, nhanSu.getMaNS(),"XNSTB");
                f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                f.setLocationRelativeTo(null);
                f.setResizable(false);
                f.setVisible(true);
                this.dispose();
            }

        } catch (IOException ex) {
            Logger.getLogger(XemNhanSuTrongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_troveActionPerformed

    private void xemNhanSuTrongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemNhanSuTrongBanActionPerformed
        try {
            int index = tableDanhSachNhanSu.getSelectedRow();
            if (index == -1) {
                throw new IOException("Bạn chưa chọn nhân sự muốn xem!");
            }

            ChiTietNhanSu f = new ChiTietNhanSu(id, dsBan_NhanSuThuocBan.get(index).getNhanSu().getMaNS(),"XNSTB");
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setLocationRelativeTo(null);
            f.setResizable(false);
            f.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thao tác thất bại!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_xemNhanSuTrongBanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDanhSachNhanSu;
    private javax.swing.JLabel text_Ban;
    private javax.swing.JLabel text_Phong;
    private javax.swing.JButton trove;
    private javax.swing.JButton xemNhanSuTrongBan;
    // End of variables declaration//GEN-END:variables
}
